### ISSUE TITLE
Integrate framework issue

### ISSUE THREAD

**Issue by SakthiKumar-iOS** [vijayviswas/LIExplorer#1]
duplicate symbols for architecture x86_64 using LIExplorer framework

**Comment by vijayviswas** [comment]
@sakthikumarmdu - Its wired I dont see any other clients complain this. Can you try download the sample code(https://github.com/vijayviswas/TestLK) and see whether you get the same error?

**Comment by SakthiKumar-iOS** [comment]
Yes i get same error in sample code, If i drag the framework in xcode and build the project i got   the above mentioned issue

**Comment by vijayviswas** [comment]
@sakthikumarmdu - I just tried and I am not seeing any error.
Also I see the x86_64 in framework Arch- armv7 i386 x86_64 arm64 
Which version of xcode and Mac os you are using?

**Comment by SakthiKumar-iOS** [comment]
Xcode version:6.2 Mac os version: 10.9.5

**Comment by vijayviswas** [comment]
@sakthikumarmdu . Sorry I was traveling . Have you got a chance to resolve this? Delete the derived directory and try. I am not seeing any error in my machine.

**Comment by SakthiKumar-iOS** [comment]
ok thanks, i will try in my mac
