### ISSUE TITLE
Logout feature

### ISSUE THREAD

**Issue by pavanSaberjack** [vijayviswas/LIExplorer#2]
Hi Vijay,
I was trying to use your frame work. Working awesome.
Just a suggestion, as I was going through the framework headers.
There is no logout method exposed. Is it intentional?

-Thanks,
Pavan

**Comment by vijayviswas** [comment]
Yes @pavanSaberjack . See below explanation.
There is no specific method to log out in OAuth 2.0 to invalidate the token. I would recommend to handle it in app level . See below code.

App level switch - authenticateLIExplorer = true // NSUSerdefaults

if (isValidToken && authenticateLIExplorer)
{

// Set authenticateLIExplorer as false
//Initialize the LIAuthorizationVC

}

If user clicks logout button in app then set the authenticateLIExplorer flag as true so next time the above check will be true and opens LIAuthorizationVC to enter user credentials.

Please let me know if you need any clarifications on this.

**Comment by pavanSaberjack** [comment]
@vijayviswas  Yes. Logout : I meant to say just invalidate token stored in NSUserdefaults only. If I knew how the tokens are stored in NSUserDefaults/Keychain I would have directly removed them. 
Anyways I will use your logic. Thanks. 👍

**Comment by vijayviswas** [comment]
@pavanSaberjack 

I have released a new version of LIExplorer with clearToken method. So above logic is not needed . All you have to do is the  call the clear Token  method when user clicks logout method.

https://github.com/vijayviswas/LIExplorer/releases/tag/4.0.0

Can you please try the latest framework and let me if it works
