### ISSUE TITLE
User navigated to other links Code=60003

### ISSUE THREAD

**Issue by ghost** [vijayviswas/LIExplorer#4]
Error Domain=User navigated to other links Code=60003 "(null)" UserInfo={Url=https://www.linkedin.com/uas/connect-captcha}

why don't you handle to captcha redirection ?
BTW Nice Framework 

Thanks
Deepak

**Comment by vijayviswas** [comment]
Deepak,
One of my other client also reported this. The problem here I am unable to
reproduce this scenario as my LI credentials never show captcha while I
logged in. I will keep investigate and let you know soon.

Vijay Viswas

**Comment by ghost** [comment]
@vijayviswas if you need i can provide details 

are able to address why this happening ?? 
duplicate content ??

**Comment by vijayviswas** [comment]
Yes pls

**Comment by insanelydeepak** [comment]
@vijayviswas 
jsontestx@gmail.com
Netset@123
PS: please remove this message after reading

**Comment by vijayviswas** [comment]
@insanelydeepak - Can you email on vijayLIExplorer@gmail.com. I dont get Captcha

**Comment by ghost** [comment]
sure , I will dig deeper and report you asap :) 
thanks

**Comment by vijayviswas** [comment]
Hope the latest sdk has resolved this issue . @insanelydeepak

**Comment by ghost** [comment]
Hi sir 
This issue fixed , you can close this 
now i request you to provide detection for cancel clicked on webview , in old version it was working good returns 6001 , but in latest sdk 6003 , so my check get fails 
Thank you very much
