### ISSUE TITLE
Headline information in get profile.

### ISSUE THREAD

**Issue by julienbiau** [vijayviswas/LIExplorer#6]
I am using your framework it works great.
But when using Linkedin SDK, i can get the headline when asking for the profile.
When using your framework, i can't get the headline.
Why does i have to do to get the headline ?
Can you update your framework to grant access to the headline ?

Thanks

Julien

**Comment by vijayviswas** [comment]
@julienbiau - I have implemented the headline. Can you please try the 6.0.0 beta and let me know if it works?
https://github.com/vijayviswas/LIExplorer/releases/tag/6.0.0

NOTE: Please try beta framework with below scenarios.
1) Delete the exsisting app and install new.
2) Upgrade the app with v6.0 framework

**Comment by vijayviswas** [comment]
This issue is fixed in v6.0
