### ISSUE TITLE
LIAuthorizationVC shows up as a black screen

### ISSUE THREAD

**Issue by bisikli** [vijayviswas/LIExplorer#7]
let liapp = LIApplication()
        liapp.clientId = clientId
        liapp.clientSecret = clientSecret
        liapp.redirectURL  = redirectUri
        liapp.state        = state
        LIExplorer.registerKey("LIExplorer_Public", with: liapp, staging: true)

Initializing like above then checking for login brings up a pitch black view controller..

**Comment by vijayviswas** [comment]
@bisikli Can you please share the xcode console log?
