### ISSUE TITLE
Setting Permissions

### ISSUE THREAD

**Issue by acsarraf** [vijayviswas/LIExplorer#8]
Is there any way to set up which permissions you want to use by code like in the LinkedIn SDK. I like using your framework as a way of providing WebView/In app authentication, but whenever i try to use getCompanyInfo for example I get returned that I am not authorized to do this. When I use the LinkedIn SDK or the REST API Helper on the LinkedIn Site this works fine. 

Thanks. 

Your project is super helpful btw.

**Comment by vijayviswas** [comment]
@theraad - Have you given all the permissions for your app in linkedin?  Also are you getting permission issue while calling any specific calls or for all calls?

r_basicprofile | r_emailaddress | rw_company_admin |w_share

If you still have issue after giving full permission then I might need the linkedin credentials to check whats happening? You can send it to  liexplorer6@gmail.com
