### ISSUE TITLE
Changes in oath2.0 urls

### ISSUE THREAD

**Issue by CarlosCarrera** [vijayviswas/LIExplorer#9]
As of last month, linkedin changed their OAuth URLS from:
`https://www.linkedin.com/uas/oauth2/authorization`
to:
`https://www.linkedin.com/oauth/v2/authorization`

Is there any posible way to change this? Thanks in advance

link: https://developer.linkedin.com/blog/posts/2018/redirecting-oauth-uas

**Comment by vijayviswas** [comment]
@CarlosCarrera  - Already framework has https://www.linkedin.com/oauth/v2/authorization. Do you see any issues
